according to FreeRADIUS developer buggy libtool on some platforms, causes radiusdS build to fail with undefined reference to lt__PROGRAM__LTX_preloaded_symbols; suggested workaround is to add -DIE_LIBTOOL_DIE to the end of the CFLAGS line in Make.inc file; see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=560355